n1 = int(input('Digite um número: '))
a = (1 * n1)
b = (2 * n1)
c = (3 * n1)
d = (4 * n1)
e = (5 * n1)
f = (6 * n1)
g = (7 * n1)
h = (8 * n1)
i = (9 * n1)
j = (10 * n1)
print('Tabuada: \n {} \n {} \n {} \n {} \n {} \n {} \n {} \n {} \n {} \n {}'.format(a, b, c, d, e, f, g, h, i, j))
