n = input('Digite algo: ')
print('Esse numero é', type(n))
print('Ele é numerico?', n.isnumeric())
print('É alfabético?', n.isalpha())
print('É um decimal?', n.isdecimal())
print('É minúsculo?', n.islower())
print('É maiúsculo?', n.isupper())
print('É um digito?', n.isdigit())
print('É alfa-numerico?', n.isalnum())
print('É espaço?', n.isspace())
print('É possivel imprimir?', n.isprintable())
print('Verificação concluída')
